/**
 * Phonebook API
 * RESTful API for Messente phonebook
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PhonebookApi) {
      root.PhonebookApi = {};
    }
    root.PhonebookApi.ResponseErrorTitle = factory(root.PhonebookApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class ResponseErrorTitle.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "Invalid data"
     * @const
     */
    "Invalid data": "Invalid data",
    /**
     * value: "Unauthorized"
     * @const
     */
    "Unauthorized": "Unauthorized",
    /**
     * value: "Missing resource"
     * @const
     */
    "Missing resource": "Missing resource",
    /**
     * value: "Conflict"
     * @const
     */
    "Conflict": "Conflict",
    /**
     * value: "General error"
     * @const
     */
    "General error": "General error"  };

  /**
   * Returns a <code>ResponseErrorTitle</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ResponseErrorTitle} The enum <code>ResponseErrorTitle</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


