/**
 * Phonebook API
 * RESTful API for Messente phonebook
 *
 * OpenAPI spec version: 0.0.4
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhonebookApi);
  }
}(this, function(expect, PhonebookApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PhonebookApi.ContactFields();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactFields', function() {
    it('should create an instance of ContactFields', function() {
      // uncomment below and update the code to test ContactFields
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be.a(PhonebookApi.ContactFields);
    });

    it('should have the property phoneNumber (base name: "phoneNumber")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property custom (base name: "custom")', function() {
      // uncomment below and update the code to test the property custom
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property custom2 (base name: "custom2")', function() {
      // uncomment below and update the code to test the property custom2
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property custom3 (base name: "custom3")', function() {
      // uncomment below and update the code to test the property custom3
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

    it('should have the property custom4 (base name: "custom4")', function() {
      // uncomment below and update the code to test the property custom4
      //var instance = new PhonebookApi.ContactFields();
      //expect(instance).to.be();
    });

  });

}));
