/**
 * Phonebook API
 * RESTful API for Messente phonebook
 *
 * OpenAPI spec version: 0.0.4
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContactEnvelope', 'model/ContactFields', 'model/ContactListEnvelope', 'model/ContactUpdateFields', 'model/EmptyObject', 'model/ErrorItem', 'model/ErrorResponse', 'model/FetchBlacklistSuccess', 'model/GroupEnvelope', 'model/GroupListEnvelope', 'model/GroupName', 'model/GroupResponseFields', 'model/NumberToBlacklist', 'model/ResponseErrorCode', 'model/ResponseErrorTitle', 'api/BlacklistApi', 'api/ContactsApi', 'api/GroupsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ContactEnvelope'), require('./model/ContactFields'), require('./model/ContactListEnvelope'), require('./model/ContactUpdateFields'), require('./model/EmptyObject'), require('./model/ErrorItem'), require('./model/ErrorResponse'), require('./model/FetchBlacklistSuccess'), require('./model/GroupEnvelope'), require('./model/GroupListEnvelope'), require('./model/GroupName'), require('./model/GroupResponseFields'), require('./model/NumberToBlacklist'), require('./model/ResponseErrorCode'), require('./model/ResponseErrorTitle'), require('./api/BlacklistApi'), require('./api/ContactsApi'), require('./api/GroupsApi'));
  }
}(function(ApiClient, ContactEnvelope, ContactFields, ContactListEnvelope, ContactUpdateFields, EmptyObject, ErrorItem, ErrorResponse, FetchBlacklistSuccess, GroupEnvelope, GroupListEnvelope, GroupName, GroupResponseFields, NumberToBlacklist, ResponseErrorCode, ResponseErrorTitle, BlacklistApi, ContactsApi, GroupsApi) {
  'use strict';

  /**
   * RESTful_API_for_Messente_phonebook.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var PhonebookApi = require('index'); // See note below*.
   * var xxxSvc = new PhonebookApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new PhonebookApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new PhonebookApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new PhonebookApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.4
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ContactEnvelope model constructor.
     * @property {module:model/ContactEnvelope}
     */
    ContactEnvelope: ContactEnvelope,
    /**
     * The ContactFields model constructor.
     * @property {module:model/ContactFields}
     */
    ContactFields: ContactFields,
    /**
     * The ContactListEnvelope model constructor.
     * @property {module:model/ContactListEnvelope}
     */
    ContactListEnvelope: ContactListEnvelope,
    /**
     * The ContactUpdateFields model constructor.
     * @property {module:model/ContactUpdateFields}
     */
    ContactUpdateFields: ContactUpdateFields,
    /**
     * The EmptyObject model constructor.
     * @property {module:model/EmptyObject}
     */
    EmptyObject: EmptyObject,
    /**
     * The ErrorItem model constructor.
     * @property {module:model/ErrorItem}
     */
    ErrorItem: ErrorItem,
    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The FetchBlacklistSuccess model constructor.
     * @property {module:model/FetchBlacklistSuccess}
     */
    FetchBlacklistSuccess: FetchBlacklistSuccess,
    /**
     * The GroupEnvelope model constructor.
     * @property {module:model/GroupEnvelope}
     */
    GroupEnvelope: GroupEnvelope,
    /**
     * The GroupListEnvelope model constructor.
     * @property {module:model/GroupListEnvelope}
     */
    GroupListEnvelope: GroupListEnvelope,
    /**
     * The GroupName model constructor.
     * @property {module:model/GroupName}
     */
    GroupName: GroupName,
    /**
     * The GroupResponseFields model constructor.
     * @property {module:model/GroupResponseFields}
     */
    GroupResponseFields: GroupResponseFields,
    /**
     * The NumberToBlacklist model constructor.
     * @property {module:model/NumberToBlacklist}
     */
    NumberToBlacklist: NumberToBlacklist,
    /**
     * The ResponseErrorCode model constructor.
     * @property {module:model/ResponseErrorCode}
     */
    ResponseErrorCode: ResponseErrorCode,
    /**
     * The ResponseErrorTitle model constructor.
     * @property {module:model/ResponseErrorTitle}
     */
    ResponseErrorTitle: ResponseErrorTitle,
    /**
     * The BlacklistApi service constructor.
     * @property {module:api/BlacklistApi}
     */
    BlacklistApi: BlacklistApi,
    /**
     * The ContactsApi service constructor.
     * @property {module:api/ContactsApi}
     */
    ContactsApi: ContactsApi,
    /**
     * The GroupsApi service constructor.
     * @property {module:api/GroupsApi}
     */
    GroupsApi: GroupsApi
  };

  return exports;
}));
